---
# role for fix_repo_check_ptf_group
# Get the latest PTF group information from PSP(Preventive Service Planning) server, and check if the latest PTF group is already
# in ptf_group_image table or already downloading.
- set_fact:
    check_ptf_group_fail: False

- name: Check and get the latest PTF group information on PSP
  ibmi_fix_group_check:
    groups: '{{ ptf_group }}'
  register: fix_group_check_result

- name: Print the latest PTF group information
  debug:
    var: fix_group_check_result

- block:
    - name: If get the latest PTF group information fail
      debug:
        msg: "Get the latest PTF group information fail, skip the rest of this role"

    - set_fact:
        check_ptf_group_fail: True
  when: fix_group_check_result.group_info is not defined

- block:
    - name: Check if ptf group information is already in catalog's ptf group information table
      ibmi_fix_repo:
        database: "{{ database }}"
        type: "ptf_group"
        action: "find"
        parameters:
          - "{{ {'ptf_group_number': fix_group_check_result.group_info[0].ptf_group_number,
          'ptf_group_level': fix_group_check_result.group_info[0].ptf_group_level,
          'release_date': fix_group_check_result.group_info[0].release_date} }}"
      register: ptf_group_find_result
      when: fix_group_check_result.group_info != []

    - name: Print find PTF group result
      debug:
        var: ptf_group_find_result

    - block:
        - name: Check if ptf group information is already in catalog's download_status table, which means ptf group is downloading.
          ibmi_fix_repo:
            database: "{{ database }}"
            type: "download_status"
            action: "find"
            parameters:
              - "{{ {'ptf_group_number': fix_group_check_result.group_info[0].ptf_group_number,
              'ptf_group_level': fix_group_check_result.group_info[0].ptf_group_level,
              'release_date': fix_group_check_result.group_info[0].release_date} }}"
          register: download_status_find_result
          when: fix_group_check_result.group_info != []

        - name: Print find download_status table result
          debug:
            var: download_status_find_result
      when: ptf_group_find_result.fail_list is defined

  when: fix_group_check_result.group_info is defined
