---
# tasks file for check_ptf
- name: clear vars for every run
  set_fact:
    ptfs: []
    ptfs_status: {}
    checked_ptf: {}
    ptfs_info: []
    not_loaded_ptfs_list: []

- name: compose ptf list and ptfs status dict
  set_fact:
    ptfs: "{{ ptfs|default([]) + [item.ptf_id] }}"
    ptfs_status: "{{ ptfs_status|default({}) | combine( {item.ptf_id: 'NON-EXISTENT'} ) }}"
  loop: '{{ check_ptf_list }}'

- name: print ptf number list to-be-checked
  debug:
    msg: 'ptf numbers to be checked: {{ ptfs }}'

- name: query the status of the request ptf
  ibmi_fix:
    fix_list: '{{ ptfs }}'
    operation: 'query'
  register: check

- name: compose check result dict
  set_fact:
    ptfs_info: "{{ check.ptf_list }}"

- name: print ptfs_info
  debug:
    var: ptfs_info

- name: compose ptfs status dict
  set_fact:
    checked_ptf: "{{ checked_ptf|default({}) | combine( {item.PTF_IDENTIFIER: item.PTF_LOADED_STATUS} ) }}"
  loop: '{{ ptfs_info | list }}'

- name: print checked_ptf
  debug:
    var: checked_ptf

- name: combine the query result and unknown ptf
  set_fact:
    ptfs_status: "{{ ptfs_status|default({}) | combine( checked_ptf|default({}) ) }}"

- name: compose not_loaded_ptfs_list
  set_fact:
    to_be_loadnumber: []
    not_loaded_ptfs_list: []

- name: compose not_loaded_ptfs_list
  set_fact:
    to_be_loadnumber: "{{ to_be_loadnumber|default([]) + [ptf_status.key] }}"
  when: ptf_status.value == 'NON-EXISTENT' or ptf_status.value == 'PERMANENTLY REMOVED' or ptf_status.value == 'NOT LOADED'
  with_dict: "{{ ptfs_status }}"
  loop_control:
    loop_var: ptf_status

- name: compose not_loaded_ptfs_list
  include_tasks: find_ptfinfo.yml
  with_list: "{{ to_be_loadnumber }}"
  loop_control:
    loop_var: ptf_id

- name: compose not_loaded_ptfs_list
  set_fact:
    #ptfs_info: "{{ ptfs_info|default([]) + [{'PTF_IDENTIFIER': ptf_status.key, 'PTF_LOADED_STATUS': 'NON-EXISTENT'}] }}"
    ptfs_info: "{{ ptfs_info + [{'PTF_IDENTIFIER': ptf_status.key, 'PTF_LOADED_STATUS': 'NON-EXISTENT'}] }}"
  when: ptf_status.value == 'NON-EXISTENT'
  with_dict: "{{ ptfs_status }}"
  loop_control:
    loop_var: ptf_status

- name: print ptfs status
  debug:
    var: ptfs_status

- name: print ptfs info
  debug:
    var: ptfs_info

- name: print to be loaded ptf list
  debug:
    var: not_loaded_ptfs_list
