---
allow_duplicates: yes
galaxy_info:
  author: Daniel Schneller
  description: Installs a sysdig based user activity tracer
  company: Rheinwerk
  license: license (GPLv3)
  min_ansible_version: 2.6
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  galaxy_tags:
    - sysdig
dependencies: []
